import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | VibeClips',
  description: 'Terms of Service for VibeClips AI Video Generator.',
  alternates: {
    canonical: '/terms',
  },
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-24 space-y-8">
      <h1 className="text-4xl md:text-5xl font-extrabold text-white">Terms of Service</h1>
      <p className="text-neutral-400">Last updated: September 14, 2026</p>
      
      <div className="prose prose-invert prose-neutral max-w-none text-neutral-300">
        <p>
          Welcome to VibeClips. By accessing or using our website and open-source software, you agree to comply with and be bound by the following Terms of Service.
        </p>
        
        <h2 className="text-2xl font-bold text-white mt-8 mb-4">1. Bring Your Own Key (BYOK) Responsibility</h2>
        <p>
          VibeClips functions by requiring you to provide your own third-party API keys (e.g., Google Gemini). 
        </p>
        <ul className="list-disc pl-6 space-y-2 my-4">
          <li>You are solely responsible for acquiring these keys legally and securely.</li>
          <li>You are responsible for any usage limits, fees, or billing associated with your personal API keys on those third-party platforms.</li>
          <li>VibeClips is not responsible for suspended accounts, API bans, or unexpected charges incurred on third-party platforms resulting from your use of this tool.</li>
        </ul>

        <h2 className="text-2xl font-bold text-white mt-8 mb-4">2. Intellectual Property</h2>
        <p>
          The procedural animations and text generated by VibeClips (via the Gemini API) are yours to use commercially or non-commercially, provided you have the legal rights to the underlying audio you upload. We claim no copyright over the videos you render.
        </p>

        <h2 className="text-2xl font-bold text-white mt-8 mb-4">3. MIT License</h2>
        <p>
          The underlying source code of VibeClips is provided under the MIT License. You are free to use, modify, and distribute the software, provided you include the original copyright notice and permission notice.
        </p>

        <h2 className="text-2xl font-bold text-white mt-8 mb-4">4. "As Is" Basis and Limitation of Liability</h2>
        <p>
          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
        </p>
        <p>
          Because VibeClips runs client-side and relies on experimental browser features (like WebCodecs), we do not guarantee that the tool will work perfectly on all browsers, devices, or operating systems. We are not liable for any lost work, failed renders, or device crashes.
        </p>
      </div>
    </div>
  );
}
